# Generated by Django 4.2.4 on 2023-10-11 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clase_taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='horarioMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniweb.dia')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniweb.hora')),
            ],
        ),
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('horario', models.ManyToManyField(through='uniweb.horarioMateria', to='uniweb.dia')),
                ('horario_taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniweb.clase_taller')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniweb.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='horarioTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniweb.clase_taller')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniweb.dia')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniweb.hora')),
            ],
        ),
        migrations.AddField(
            model_name='horariomateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniweb.materia'),
        ),
        migrations.AddField(
            model_name='clase_taller',
            name='horario',
            field=models.ManyToManyField(through='uniweb.horarioTaller', to='uniweb.dia'),
        ),
        migrations.AddField(
            model_name='clase_taller',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniweb.profesor'),
        ),
    ]
